Release prep
NCAR/geocat-comp pull request #101
Opened 2021-02-05 20:12 UTC by pilotchute

2021-02-10 16:20 UTC, pilotchute commented
Please review this update to geocat-comp that implements f2py as the fortran backend.

2021-02-10 19:52 UTC, erogluorhan requested changes
Looks good mostly. A few points:

1) This PR is adding Github actions for build tests but not removing CircleCI bindings. Why?
2) In build environments (**build_envs** folder), there is still `geocat-ncomp` dependency but not `f2py` dependency.
3) Please address inline comments.

2021-02-10 19:52 UTC, erogluorhan commented on meta.yaml
> +  version: "2021.01.1"
Two points:
1. May it be better to say "2021.02.0"?
2. Looks like "version" is being used in at least two different places (meta.yml and setup.py). Instead of manually handling in multiple locations, please do not delete **version.py** and make use of it.

2021-02-10 19:52 UTC, erogluorhan commented on .github/workflows/build_test.yml
> +          conda env create --file build_envs/environment_$(uname).yml
Please move these two lines (`conda env create` and `conda activate`) to above "conda_env" step.

2021-02-10 19:52 UTC, erogluorhan commented on setup.py
> +version = '2021.01.1'
Two points:
1. May it be better to say "2021.02.0"?
2. Looks like "version" is being used in at least two different places (meta.yml and setup.py). Instead of manually handling in multiple locations, please do not delete **version.py** and make use of it.

2021-02-10 19:52 UTC, erogluorhan commented on setup.py
> -      version=__version__,
In regard to above version comment of mine, I think we should be still referring to version.py like here.

2021-02-10 19:52 UTC, erogluorhan commented on src/geocat/comp/version.py
> -__version__ = "0.2"
Again, I prefer not to remove **version.py**, but may be we can move it to root directory?

2021-02-11 22:54 UTC, pilotchute commented on meta.yaml
> +  version: "2021.01.1"
setup.py now pulls version info from meta.yaml. no need for a version.py file.

2021-02-11 23:06 UTC, pilotchute commented on src/geocat/comp/version.py
> -__version__ = "0.2"
version now stored in meta.yaml

2021-02-11 23:12 UTC, pilotchute commented on .github/workflows/build_test.yml
> +          conda env create --file build_envs/environment_$(uname).yml
conda setup broken into mutiple steps, same with build test, much clearer on failures now

2021-02-12 00:18 UTC, erogluorhan requested changes
In build environments (build_envs folder), please convert geocat-ncomp dependency to geocat-f2py dependency

2021-02-12 00:25 UTC, pilotchute commented
> In build environments (build_envs folder), please convert geocat-ncomp dependency to geocat-f2py dependency

Done.

2021-02-12 00:28 UTC, erogluorhan approved these changes
Great job!

2021-02-12 00:30 UTC, pilotchute commented
Will merge once the tests finish.

2021-02-12 00:48 UTC, anissa111 approved these changes
This looks great, thank you for getting this together!

2021-02-12 00:52 UTC, merged