Implementation of max_daylight
NCAR/geocat-comp pull request #125
Opened 2021-03-10 01:08 UTC by anissa111

Addresses #116 

Summary of changes: 
- Implements NCL's `daylight_fao56` as `max_daylight` in geocat-comp
- Adds a ncl script that produces an ncl file for creating a ground truth for testing
- Implements basic tests against the ncl ground truth

2021-03-10 14:23 UTC, andersy005 commented on src/geocat/comp/crop.py
> +        save_attrs = jday.attrs
I presume you are keeping these so they can be used in the returned output. However, I don't see them being accessed

2021-03-10 14:46 UTC, dcherian commented on test/test_max_daylight.py
> +        client = dd.Client(cluster)
In general a nice pattern is

``` python
# please copy this over, it isn't public API
from xarray.tests import raise_if_dask_computes

with raise_if_dask_computes():
    # will raise if max_daylight calls .compute either directly
    # or indirectly (as with np.asarray)
    actual = max_daylight(...) 

expected = ...
np.testing.assert_allclose(actual, expected)  # will call compute and check values
```

This makes sure your functions are lazy and avoid indirect computes

2021-03-10 14:47 UTC, dcherian commented on src/geocat/comp/crop.py
> +    jday = np.asarray(jday)
please copy over `utils.is_duck_array` it isn't public API and could change

2021-03-10 14:51 UTC, andersy005 commented on src/geocat/comp/crop.py
> +    jday = np.asarray(jday)
Good catch. I just assumed that since it wasn't hidden with `_`, it must be part of the public API

2021-03-10 14:52 UTC, dcherian commented on src/geocat/comp/crop.py
> +    jday = np.asarray(jday)
https://xarray.pydata.org/en/stable/faq.html#what-parts-of-xarray-are-considered-public-api =) unfortunately xarray codebase does not consistently follow that convention

2021-03-10 16:54 UTC, anissa111 commented on src/geocat/comp/crop.py
> +        save_attrs = jday.attrs
Yup you're right, thanks for the catch! This was a copy paste oversight.

2021-03-15 17:03 UTC, anissa111 commented on src/geocat/comp/crop.py
> +    jday = np.asarray(jday)
I apologize if I've missed the answer already in the comment thread, but is ```is_duck_array()``` the right way to proceed?

2021-03-15 17:06 UTC, anissa111 commented on test/test_max_daylight.py
> +        out = map_blocks(max_daylight, jday, lat).compute()
Thanks for the catch, addressed!

2021-03-15 17:35 UTC, dcherian commented on src/geocat/comp/crop.py
> +    jday = np.asarray(jday)
Yes, just copy it over
``` python
def is_duck_array(value):
    """ Returns True when ``value`` is array-like. """
    if isinstance(value, np.ndarray):
        return True
    return (
        hasattr(value, "ndim")
        and hasattr(value, "shape")
        and hasattr(value, "dtype")
        and hasattr(value, "__array_function__")
        and hasattr(value, "__array_ufunc__")
    )
```

2021-03-30 04:21 UTC, pilotchute commented
@anissa111 Pre-commit hooks have been updated.

2021-03-30 16:57 UTC, anissa111 commented on test/test_max_daylight.py
> +        client = dd.Client(cluster)
Coming back around to this, we had some issues using pytest fixtures, but we have addressed this redundant cluster initiations with unittest's ```setUpClass()``` with a client established once in there.

2021-03-30 17:24 UTC, andersy005 commented on src/geocat/comp/crop.py
> +            "WARNING: max_daylight has limited validity for abs(lat) > 55 ")
An additional test for this, maybe?

```python
def test_lat_bound_warnings():
    with pytest.warns(UserWarning):
       	max_daylight(10, 56.)
```

2021-03-30 17:29 UTC, andersy005 commented on src/geocat/comp/crop.py
> +    elif (abs(lat) > 66).all():
This comment above says that the code should error when `(abs(lat) > 66).all()` is `True`. However, in the implementation a warning is raised instead. Should this error or warn the user? If it's the latter, the comment above should be updated

2021-03-30 20:14 UTC, anissa111 commented on src/geocat/comp/crop.py
> +        raise ValueError('max_daylight: inputs must have at most one dimension')
Absolutely, done!

2021-03-30 20:41 UTC, anissa111 commented on src/geocat/comp/crop.py
> +            "WARNING: max_daylight has limited validity for abs(lat) > 55 ")
Added!

2021-03-30 20:52 UTC, anissa111 commented on src/geocat/comp/crop.py
> +            hasattr(value, "__array_ufunc__"))
Yeah, I have moved it, thank you!

2021-03-30 20:58 UTC, andersy005 commented on src/geocat/comp/crop.py
> +from comp_util import _is_duck_array
```suggestion
from .comp_util import _is_duck_array
```

2021-03-30 21:12 UTC, anissa111 commented on src/geocat/comp/crop.py
> +from comp_util import _is_duck_array
Yup, thank you!

2021-03-30 22:09 UTC, andersy005 approved these changes
Looks good to me 👍🏽

2021-03-30 22:12 UTC, pilotchute approved these changes
Approved.

2021-03-31 00:09 UTC, erogluorhan commented on src/geocat/comp/crop.py
> +    """Computes maximum number of daylight hours as describe in the Food and
"... as described ..."

2021-03-31 00:21 UTC, erogluorhan commented on test/test_max_daylight.py
> +from geocat.comp.crop import max_daylight
The current [code coverage report ](https://codecov.io/gh/NCAR/geocat-comp/src/9b7358dfc34620348e83ee49d56d9de69a19bdcb/src/geocat/comp/crop.py)of this function shows as if almost nothing is covered by the tests (despite the reality). For the code coverage to work properly, please re-write this import line as follows:

```
# Import from directory structure if coverage test, or from installed
# packages otherwise
if "--cov" in str(sys.argv):
    from src.geocat.comp import max_daylight
else:
    from geocat.comp import max_daylight
```

This is because, as the comment suggests, when code coverage is analyzing, it uses the directory structure, but other that code coverage, we want to test our namespace from the installed packages (to ensure this function will be flawless when geocat.comp is installed via conda). 

In relation to above namespace testing purposes, our imports should be `from geocat.comp import ...` instead of `from geocat.comp.crop import ...` because we want to test if the function can be directly imported from `geocat.comp` namespace.

2021-03-31 00:25 UTC, anissa111 commented on src/geocat/comp/comp_util.py
> +def _is_duck_array(value):
No, actually xarray. This is something from their non-public API. It was discussed in one of the earlier resolved conversations on this PR.

2021-03-31 17:31 UTC, anissa111 commented on src/geocat/comp/crop.py
> +     Crop evapotranspiration - Guidelines for computing crop water
Good catch, thank you!

2021-03-31 17:33 UTC, anissa111 commented on src/geocat/comp/crop.py
> +    """Computes maximum number of daylight hours as describe in the Food and
Haha, yup! Thank you!

2021-03-31 21:00 UTC, erogluorhan requested changes
This is great; just one final request:

Look at the [code coverage report](https://codecov.io/gh/NCAR/geocat-comp/src/8d630b2997ad10e495366f1e2150c1b88accc511/src/geocat/comp/crop.py) and you will see none of your unit tests covers the case of `abs(lat) > 55` (Lines 53-55). Could you please add a simple unit test case to cover that warning block?

In addition, the warning message of that case says "calculation not possible"; I am wondering why the code is still being continued after that (i.e. why not throwing an error).

2021-03-31 21:03 UTC, anissa111 commented
> This is great; just one final request:
> 
> Look at the [code coverage report](https://codecov.io/gh/NCAR/geocat-comp/src/8d630b2997ad10e495366f1e2150c1b88accc511/src/geocat/comp/crop.py) and you will see none of your unit tests covers the case of `abs(lat) > 55` (Lines 53-55). Could you please add a simple unit test case to cover that warning block?

Oh! There is actually, but it appears that I have a bug so that line is reachable. I'll fix it now.

2021-03-31 21:37 UTC, erogluorhan approved these changes
Great job!

Note: macos tests are queued but did not start yet (Probably something specific to Github actions servers). When they start and pass, please merge it.

2021-04-01 00:42 UTC, merged