heat_index
NCAR/geocat-comp pull request #138
Opened 2021-04-07 02:08 UTC by anissa111

This is a work in progress PR for the implementation of `heat_index_nws`, renamed here `heat_index`, as described in [S@S Scenario 2](https://github.com/NCAR/science-at-scale/issues/2).

2021-04-12 21:27 UTC, anissa111 commented
Just a note, during the testing process for heat_index, @michaelavs and I discovered a bug in the original ncl. Following the original [NWS equations](https://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml), one of the "adjustments" was not being calculated in the ncl function. The values produced with this python version were verified by hand according to the original equations where the bug was present. This is why the ncl test script and ncl ground truth file were removed from this function's testing.

2021-04-13 19:09 UTC, erogluorhan requested changes
Looks great; please address a few inline comments.

2021-04-13 19:09 UTC, erogluorhan commented on src/geocat/comp/heat_index.py
> +def heat_index(t, rh, alt_coef=False):
How about renaming the arguments to be more PEP-friendly? Maybe `temperature`, `relative_humidity` or `rel_hum`, `alternate_coeffs`, or so?

2021-04-13 19:09 UTC, erogluorhan commented on src/geocat/comp/heat_index.py
> +    c = [
Arguments like this may need renaming. `c` says nothing when reading the code.

2021-04-13 19:09 UTC, erogluorhan commented on test/test_heat_index.py
> +    from src.geocat.comp.heat_index import heat_index
Please avoid using the script name (i.e. `.heat_index` in this case) when importing in test scripts. This is because we are trying to test against the packages/namespace, not individual scripts. So, use:

`from src.geocat.comp import heat_index`

2021-04-13 19:09 UTC, erogluorhan commented on test/test_heat_index.py
> +    from geocat.comp.heat_index import heat_index
Above comment applies here, too.

2021-04-13 19:09 UTC, erogluorhan commented on test/test_heat_index.py
> +class Test_heat_index(unittest.TestCase):
Please try to write one more test case, if possible, that covers the following `else` case:

![image](https://user-images.githubusercontent.com/32553057/114607154-66768d80-9c59-11eb-99f9-e9abf4ef5cb6.png)

2021-04-13 20:04 UTC, anissa111 commented on src/geocat/comp/wkSpaceTime.py
> +def wkSpaceTime():
Oops, it was pulled over from another branch by mistake, deleted!

2021-04-13 21:18 UTC, anissa111 commented on src/geocat/comp/heat_index.py
> +from geocat.comp import _is_duck_array
You're right, I'd prefer to not include it in the geocat.comp namespace. Would not including it allow us to remove it from the internal api documentation, as well?

2021-04-14 21:21 UTC, anissa111 commented on test/test_heat_index.py
> +    from src.geocat.comp.heat_index import heat_index
Right, thank you! I did it that was initially because of some namespace issues, but it appears to have solved itself.

2021-04-14 21:32 UTC, anissa111 commented on src/geocat/comp/heat_index.py
> +from geocat.comp import _is_duck_array
Okay, done!

2021-04-14 21:37 UTC, anissa111 commented on test/test_heat_index.py
> +class Test_heat_index(unittest.TestCase):
Done!

2021-04-15 15:03 UTC, michaelavs approved these changes
This looks good to me!

2021-04-15 15:40 UTC, andersy005 commented on src/geocat/comp/heat_index.py
> +
@anissa111, 

I am curious about why this computation works on 1d arrays only. if I understand correctly, we should be able to compute the heat index as long as `temperature` and `relative_humidity` array shapes are the same/compatible. 

E.g.: Assuming temperature and relative_humidity are 2D arrays: `temperature(lat, lon)` and `relative_humidity(lat, lon)`. This should/would yield `heat_index` with the following dimensionality: `heat_index(lat, lon)`, right? 



If the computation requires 1D arrays, could we accept n-dimensional arrays as inputs and then use [NumPy's ravel()](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html) to create a 1D array view that gets used in the calculation?

2021-04-15 19:54 UTC, anissa111 commented on src/geocat/comp/heat_index.py
> +
Thank you for this input! The way the calculation was set up did require 1D arrays. @erogluorhan and I have reworked the calculation to be able to accept multidimensional arrays in the most recent version.

2021-04-16 00:06 UTC, erogluorhan approved these changes
It looks great!

2021-04-16 01:23 UTC, merged