Fourier Filters
NCAR/geocat-comp pull request #145
Opened 2021-04-19 22:01 UTC by pilotchute

Getting close to ready for a pull.

2021-04-20 04:37 UTC, erogluorhan submitted a review, later dismissed
Will provide a deeper review but I noticed a quick thing for now: Please add docs (internal & user APIs etc.)

2021-04-29 15:57 UTC, pilotchute commented
@erogluorhan @anissa111 
Ready for review and merge

2021-04-29 17:50 UTC, erogluorhan commented
> Will provide a deeper review but I noticed a quick thing for now: Please add docs (internal & user APIs etc.)

@pilotchute

2021-04-29 17:59 UTC, erogluorhan requested changes
The function and unit test implementations are perfect! 

Please address a few inline comments and don't forget adding documentation (user API etc.) though.

2021-04-29 17:59 UTC, erogluorhan commented on test/test_fourier_filters.py
> +    t_data = (np.sin(t * m.tau) / 0.1 + np.sin(2 * t * m.tau) / 0.2 +
If I am not missing a nuance, these input data are the same among several test cases. Please define them in a common place to avoid code duplication.

2021-04-29 17:59 UTC, erogluorhan commented on src/geocat/comp/fourier_filters.py
> +    """Filter a dataset by frequency. This function allowes for low_pass, high_
What were the NCL functions that are addressed with these Fourier functions? How should we let people know that? Maybe adding some references in the functions' docstrings, or something else?

2021-04-29 18:29 UTC, anissa111 requested changes
This looks good, just a few inline comments below.

Also is there a reason that dask tests were not included in the unittests?

2021-04-29 18:29 UTC, anissa111 commented on src/geocat/comp/fourier_filters.py
> +    >>>import xarray as xr
There should be a space here for all the docstring examples. Also, you're never importing the fourier function itself in the examples.
```suggestion
    >>> import xarray as xr
```

2021-04-29 18:29 UTC, anissa111 commented on src/geocat/comp/fourier_filters.py
> +    cfl_index = m.floor(cutoff_frequency_low / resolution)
Is there a reason you're using the math functions instead of the numpy functions here?

2021-04-29 18:29 UTC, anissa111 commented on src/geocat/comp/fourier_filters.py
> +    signal : numpy.ndarray, xr.DataArray,
Are we requiring numpy or xarray and not allowing for list input?

2021-05-01 02:09 UTC, pilotchute commented on src/geocat/comp/fourier_filters.py
> +    >>>import xarray as xr
done

2021-05-01 02:10 UTC, pilotchute commented on src/geocat/comp/fourier_filters.py
> +    cfl_index = m.floor(cutoff_frequency_low / resolution)
No particular reason. math functions are "more native" and sliiiiightly faster. And I used math because I have unresolved java habits. :)

2021-05-01 02:12 UTC, pilotchute commented on src/geocat/comp/fourier_filters.py
> +    signal : numpy.ndarray, xr.DataArray,
In order to run the fft, we need the data in a numpy array, we could turn a nested list into a numpy array, and then call to_list later. But I really do not expect anyone to ever call this function against a list.

2021-05-01 03:53 UTC, erogluorhan commented on docs/internal_api/index.rst
> +   geocat.comp.fourier_filters.fourier_bank_block
Let us not list these functions in the internal API and only list them in user API to avoid any confusion. This is because they all are in the namespace and can be called by the user, and there is no specific internal usage of them (even though `fourier_filter` can be used as an internal function by the others).

2021-05-01 03:53 UTC, erogluorhan commented on docs/user_api/index.rst
> +   geocat.comp.fourier_filters.fourier_bank_block
Typo: `_bank_block`

2021-05-01 04:07 UTC, pilotchute commented on docs/user_api/index.rst
> +   geocat.comp.fourier_filters.fourier_bank_block
thanks, I was having trouble finding the error.

2021-05-01 04:15 UTC, erogluorhan commented on src/geocat/comp/fourier_filters.py
> +    """Filter a dataset by frequency. This function allowes for low_pass, high_
Per our discussion in the meeting, I think we are good with this as long as we add  usage examples for `smthClmDay` and `rmMonAnnCyc` functions under GeoCAT-examples. I do not have a strong preference about whether to put a statement into the docstrings here or not to put.

2021-05-01 04:49 UTC, erogluorhan approved these changes
Looks great to me!

2021-05-02 03:12 UTC, pilotchute commented on src/geocat/comp/fourier_filters.py
> +    """Filter a dataset by frequency. This function allowes for low_pass, high_
I don't think a statement belongs in the docstring, but my opinion isn't strong.

2021-05-02 13:31 UTC, erogluorhan commented on src/geocat/comp/fourier_filters.py
> +    """Filter a dataset by frequency. This function allowes for low_pass, high_
I agree

2021-05-03 17:02 UTC, pilotchute commented
@anissa111 Would you re-review, are we ready to merge this?

2021-05-03 17:07 UTC, anissa111 approved these changes
Looks good!

2021-05-03 17:10 UTC, merged