Added `cftime` as a dependency
NCAR/geocat-comp pull request #175
Opened 2021-08-10 17:28 UTC by hCraker

The latest geocat-comp conda releases (v2021.8.0) has `cftime` as a dependency, but it isn't listed in `meta.yml` or the other build and documentation files. This PR addresses this issue.

Files to change:
- [x] build/environment.yml
- [ ] build/upstream-dev-environment.yml
- [x] docs/conda_environment.yml
- [ ] docs/installation.rst
- [x] INSTALLATION.md
- [x] meta.yaml
- [x] requirements.txt

2021-08-10 23:57 UTC, pilotchute requested changes

2021-08-10 23:57 UTC, pilotchute commented on build_envs/environment.yml
> +  - numpy=1.19.0
This is incompatible with geocat-f2py's `numpy >= 1.20.2` requirement. 
Is there a reason for this restriction?

2021-08-11 13:00 UTC, erogluorhan commented on build_envs/environment.yml
> +  - numpy=1.19.0
Good catch! Heather and I worked on this yesterday and attempted to fix an issue, which turned out not related to Numpy. So, I reverted this version pin now.

2021-08-11 13:01 UTC, erogluorhan approved these changes

2021-08-11 16:05 UTC, merged