Update skewt_params
NCAR/geocat-comp pull request #178
Opened 2021-08-17 15:56 UTC by michaelavs

Updates to use MetPy's showalter index function

2021-08-17 16:14 UTC, erogluorhan commented on src/geocat/comp/skewt_params.py
> -def showalter_index(pressure, temperature, dewpt):
Existing GeoCAT-comp users might have used this function through our conda releases so far; thus, it may not be a good idea to immediately remove such a function you provided in your user API. A few alternatives to handle this instead of directly removing it:

- You may put a deprecation message into this function that states its functionality will be available via get_skewt_params from now on and this function will be deprecated (i.e. actually removed) in the upcoming version releases. 
- You could still continue providing this function signature, which would simply be a function call to metpy's function.

2021-08-17 16:14 UTC, erogluorhan commented on test/test_skewt_params.py
> +    expected = [14.82771069] * units.delta_degree_Celsius
What is your finding about this calculation discrepancy?

2021-08-17 16:14 UTC, erogluorhan commented on test/test_skewt_params.py
> +    expected = 'Plcl= 747 Tlcl[C]= 6 Shox= 15 Pwat[cm]= 5 Cape[J]= 0'
The same question as above

2021-08-17 16:36 UTC, michaelavs commented on test/test_skewt_params.py
> +    expected = [14.82771069] * units.delta_degree_Celsius
I think it was just left over from some other test values. I did the calculation by hand and got a value of around 15 which is consistent with what the function returned. I also ran the code against skewt_2_2 from examples and got a consistent value with that data as well.

2021-08-17 16:49 UTC, michaelavs commented on src/geocat/comp/skewt_params.py
> -def showalter_index(pressure, temperature, dewpt):
I decided to go with the second option and keep the function signature and then changing the function to call MetPy's function

2021-08-17 19:26 UTC, erogluorhan commented on test/test_skewt_params.py
> +    expected = [14.82771069] * units.delta_degree_Celsius
I think I am missing some insights here. Please see my one-by-one questions for your explanation:

> I think it was just left over from some other test values. I did the calculation by hand and got a value of around 15...

`test_skewt_params.py` has only two changes in [its history](https://github.com/NCAR/geocat-comp/commits/main/test/test_skewt_params.py) (one is its initiation, the other is what we addressesd recently due to MetPy's reversioning from 1.0 to 1.1). The expected value in that first commit in the history was "21.353962321924012" and then it has had a very slight change to "21.35395610431048" after MetPy's 1.1 release. So, "21.353xxx" was what our code always generated with this test code. I can't get why you are now able to calculate about 15 by hand. Was that about 15 or 21 previously?

> I also ran the code against skewt_2_2 from examples and got a consistent value with that data as well.

I can remember that we also had some discrepencies with what our code generated and what was in skewt_2_2 example. Knowing you got a consistent value with skewt_2_2 by using MetPy's implementation, should we assume our implementation somehow had a wrong calculation, and it is now fixed with MetPy's implementation?

2021-08-31 15:17 UTC, erogluorhan requested changes

2021-08-31 15:17 UTC, erogluorhan commented on src/geocat/comp/skewt_params.py
> +    SI = T500 - Tp500
`SI` is showalter index, right? Returned `shox` also stands for showalter index. How about naming them the same to have conistency between docstring and code?

2021-08-31 15:17 UTC, erogluorhan commented on test/test_skewt_params.py
> +    """Testing for Showalter Index only. While MetPy handles all five
How about moving the explanation of overall testing approach (i.e. testing only showalter index) of this docstring to the beginning of this file instead? Seeing `CAPE` under `test_shox_vals` might be a bit confusing.

2021-08-31 15:17 UTC, erogluorhan commented on test/test_skewt_params.py
> +test_shox_vals()
When we use `pytest`, we don't explicitly call these functions. Please check other test files and change this accordingly to use `pytest` with the best practices.

2021-09-03 04:39 UTC, erogluorhan approved these changes

2021-09-03 15:20 UTC, merged