Gradients
NCAR/geocat-comp pull request #256
Opened 2022-09-22 23:18 UTC by pilotchute

Draft PR for gradients.

2022-10-03 22:52 UTC, pilotchute commented
Checks are passing.
Moving out of draft phase.

2022-10-04 19:38 UTC, anissa111 reviewed
I've left a few comments below. 

Also, I think we could do more with the docstrings here (apart from what I've already mentioned), but I think it will be fine to wait until the documentation changes are merged before taking a crack at that because we'll likely have to go back over it anyway.

2022-10-04 19:38 UTC, anissa111 commented on src/geocat/comp/skewt_params.py
> -        A string element with the format "Plcl=<value> Tlcl[C]=<value> Shox=<value> Pwat[cm]=<value> Cape[J]=<value>" where:
What's going on with the changes in this file? I think this might be supposed to be in a different PR

2022-10-04 19:38 UTC, anissa111 commented on test/test_fourier_filters.py
> +if '--cov' in str(sys.argv):
Why this change here?

2022-10-04 19:38 UTC, anissa111 commented on test/test_spherical.py
> +    test_scale_np = None
I think this should probably be in a different PR as well. Possibly related to #263?

2022-10-04 19:38 UTC, anissa111 commented on src/geocat/comp/comp_util.py
>      if isinstance(value, np.ndarray):
I think we should remove the rest of the changes to this file since the new util functions were removed

2022-10-04 19:38 UTC, anissa111 commented on src/geocat/comp/gradient.py
> +        longitudinal and latitudinal gradients calculated using th WGS84 geoid.
A tiny usage example would be cool here.

Also, we should talk about converting your working notebooks into something we can add to the geocat-comp gallery after this is all merged in

2022-10-04 19:38 UTC, anissa111 commented on test/test_gradient.py
> +        cls.results_lat = cls.results[1]
Feel free to disagree with me, but I think the actual function running should be performed in the tests themselves, not during setup.

2022-10-04 19:38 UTC, anissa111 commented on src/geocat/comp/gradient.py
> +
I think we could expand on what methods you're using in the function in the docstring, thoughts?

Additionally, we still need to add the warnings we've discussed about the edge removal and the lack of dask compatibility

2022-10-04 19:39 UTC, pilotchute commented on src/geocat/comp/skewt_params.py
> -        A string element with the format "Plcl=<value> Tlcl[C]=<value> Shox=<value> Pwat[cm]=<value> Cape[J]=<value>" where:
I never intentionally edited that file, I'll revert it.

2022-10-04 19:40 UTC, pilotchute commented on test/test_fourier_filters.py
> +if '--cov' in str(sys.argv):
Was a cleanup because I was using that test file for reference and it bothered me, not needed in this pr, will remove if requested.

2022-10-04 19:41 UTC, pilotchute commented on test/test_spherical.py
> +    test_scale_np = None
This prevents issues due to accessing class method prior to instantiation of the class, will move to different pr if needed.

2022-10-04 19:41 UTC, pilotchute commented on src/geocat/comp/comp_util.py
>      if isinstance(value, np.ndarray):
sure

2022-10-04 19:43 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +        longitudinal and latitudinal gradients calculated using th WGS84 geoid.
Yeah notebooks are currently in geocat-scratch/akootz, will get them cleaned up and added to wherever as a second proirity while preparing geocat-viz tutorial.

2022-10-04 19:44 UTC, pilotchute commented on test/test_gradient.py
> +        cls.results_lat = cls.results[1]
fine by me. since we get both dimensions in one call, I figured it would be best to call once, then have the checks be separate, but no harm in running it twice.

2022-10-04 19:45 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +
yeah the warnings about data shape changes are needed, though it is fully dask compatible.

2022-10-04 19:46 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +
just not n-dimension compatible, since it requires 2d arrays.

2022-10-04 19:50 UTC, anissa111 commented on src/geocat/comp/gradient.py
> +
Oh, great! In that case, could you add dask compatibility tests?

2022-10-04 19:51 UTC, anissa111 commented on test/test_gradient.py
> +        cls.results_lat = cls.results[1]
Or combining the two tests in to one?

2022-10-04 19:51 UTC, anissa111 commented on src/geocat/comp/gradient.py
> +        longitudinal and latitudinal gradients calculated using th WGS84 geoid.
Yeah, understood

2022-10-04 19:52 UTC, anissa111 commented on test/test_fourier_filters.py
> +if '--cov' in str(sys.argv):
Yeah let's remove it here and re-address it in the future testing changes PRs

2022-10-04 20:26 UTC, anissa111 commented on test/test_spherical.py
> +    test_scale_np = None
Yeah, why don't we move this over to #263 when we get a branch going on that

2022-10-06 17:05 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +
Sure should be simple.

2022-10-06 23:31 UTC, pilotchute commented on test/test_gradient.py
> +        cls.results_lat = cls.results[1]
I'd rather run the tests twice, and have two failure messages than have one failure for two possible causes.

2022-10-07 19:35 UTC, erogluorhan reviewed
Thanks for putting this together! Please address a few inline comments.

2022-10-07 19:35 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +# '''
Please document for future why we need the below commented-out codes to be kept

2022-10-07 19:35 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +d2r = 1.74532925199432957692369e-02  # degrees to radians conversion factor
May `DEG_TO_RAD` better compatible with PEP8, not sure though?

2022-10-07 19:35 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +def rad_lat_wgs84(lat: SupportedTypes,):
Is this really intended to be in the user API? (Doesn't seem so as it is not imported in __init__.py). If not, then please name accordingly with leading underscores,  remove from the user API index.rst, and instead add into internal API index.rst.

2022-10-07 19:35 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +def arc_lat_wgs84(lat: SupportedTypes,):
The same with the previous comment regarding user API.

2022-10-07 19:35 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +def arc_lon_wgs84(
Same with the previous comment

2022-10-07 19:35 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +    ellipsoid.
Please try documenting if there are any limitations of the current implementation.

2022-10-13 21:31 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +def rad_lat_wgs84(lat: SupportedTypes,):
It is intended for the user api. The values used to determine distance along the wgs84 cannot be hidden from the end users, as it may become important in later data analysis.

2022-10-13 21:31 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +def arc_lat_wgs84(lat: SupportedTypes,):
The same with the previous comment regarding user API.

2022-10-13 21:31 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +def arc_lon_wgs84(
Same with the previous comment

2022-10-13 21:33 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +    ellipsoid.
Will do

2022-10-13 21:37 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +# '''
I have plans to come back through to improve the function a bit, to avoid having to trim the edges of the dataset, and to consider just using a numpy style gradient rather a left-right gradient average. 

I plan to keep the comment block in as a reference to the "optimal" output, that was also too slow to publish.

2022-10-14 02:11 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +d2r = 1.74532925199432957692369e-02  # degrees to radians conversion factor
It is only used once, on line 117, I'll just move the constant down there.

2022-10-14 20:40 UTC, erogluorhan commented on src/geocat/comp/gradient.py
> +# '''
Please put a similar explanation to the beginning of the commented-out code block.

2022-10-17 19:41 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +# '''
Yeah I had an improvement to the underlying implementation that I am content enough with that I see no reason to retain the elementwise implementation.

2022-10-17 19:58 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +
dask compatibility tests added.

2022-10-17 20:00 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +# '''
it's been removed.

2022-10-17 20:02 UTC, pilotchute commented on test/test_fourier_filters.py
> +if '--cov' in str(sys.argv):
done

2022-10-17 20:06 UTC, pilotchute commented on test/test_spherical.py
> +    test_scale_np = None
reverted for now, will add in for a misc improvement iteration task.

2022-10-17 20:10 UTC, pilotchute commented on src/geocat/comp/comp_util.py
>      if isinstance(value, np.ndarray):
reverted.

2022-10-17 23:58 UTC, erogluorhan approved these changes

2022-10-18 03:32 UTC, anissa111 requested changes
I've pushed an extremely minor change to the math blocks that weren't working on remote or local.

I've also included some comments below, but then I think we'll be good to merge!

2022-10-18 03:32 UTC, anissa111 commented on src/geocat/comp/__init__.py
> +from .gradient import gradient
If the other functions are intended to be public API, they should be included here, yes?

```suggestion
from .gradient import gradient, arc_lon_wgs84, arc_lat_wgs84, rad_lat_wgs84
```

2022-10-18 03:32 UTC, anissa111 commented on src/geocat/comp/gradient.py
> +
Since these are public, I think we should include the parameters and returns sections in the docstrings here and in the other functions.

2022-10-18 16:30 UTC, pilotchute commented on docs/user_api/index.rst
> +   geocat.comp.interpolation.interp_hybrid_to_pressure
you are correct.

2022-10-19 17:34 UTC, pilotchute commented on src/geocat/comp/gradient.py
> +
done

2022-10-20 02:22 UTC, anissa111 approved these changes

2022-10-20 02:23 UTC, merged