add climatology_average example
NCAR/geocat-comp pull request #341
Opened 2023-02-02 17:33 UTC by jukent

2023-02-02 20:47 UTC, hCraker reviewed
Don't forget to add the example to `docs/examples.rst` so that it shows up on the website. Once you do that, I can review this.

2023-02-03 00:35 UTC, hCraker commented
I forgot to mention that you also have to add your example to `docs/notebook-examples.txt` for the card to show up. Sorry!

2023-02-03 00:40 UTC, hCraker commented
To make the card for the new example, you'll need a thumbnail. I'd recommend using a placeholder for now or using the thumbnail from the other example. Once this PR is all done and the plot is in its final state, then you can make a more appropriate thumbnail.

2023-02-03 15:33 UTC, jukent commented
I'm not seeing that file anywhere in the repository?

2023-02-03 15:34 UTC, jukent commented
Oh it's in the `.gitignore`? Should we change that? That is unexpected unless that file is rebuilt by GH.

2023-02-03 16:41 UTC, anissa111 commented
@jukent @hCraker It's not actually `docs/notebook-examples.txt` you need to add to. That's a file that's generated/remade when the docs are made. 

You'll actually want to add it as an entry in `docs/gallery.yml` to add it to the gallery page with an appropriate thumbnail.

2023-02-03 16:43 UTC, jukent commented
That makes sense. Thanks @anissa111 and @hCraker. I will do that.

2023-02-03 16:47 UTC, hCraker commented
Whoops! Thanks for the clarification @anissa111. I was doing me best to infer based on your last examples PR, but I missed a few things

2023-02-03 16:48 UTC, anissa111 commented
Another thing to add to the PR standards checklist!

2023-02-03 16:49 UTC, jukent commented
> 

@hCraker stop replying to GitHub you're supposed to have the day off 💻

2023-02-09 18:24 UTC, hCraker requested changes
Pretty good just some formatting changes and a bug.

2023-02-09 18:24 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "ax.set_xlabel('Time')\n",
I'm getting an attribute error here since `ax` is a list of axes objects. 
`AttributeError: 'numpy.ndarray' object has no attribute 'set_xlabel'`

Changing this line to add the label to the bottom set of axes only is how you can get the label to show up properly.

```suggestion
        "ax[2].set_xlabel('Time')\n",
```

2023-02-09 18:24 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "plt.show();"
This figure doesn't show up on the rendered notebook. Did you render this block before pushing your changes? Also, the `;` shouldn't be needed
```suggestion
        "plt.show()"
```

2023-02-10 02:30 UTC, anissa111 commented on docs/gallery.yml
> +  thumbnail: _static/thumbnails/sphx_glr_calendar_average_example.png
This example should have its own thumbnail

2023-02-10 16:00 UTC, jukent commented on docs/gallery.yml
> +  thumbnail: _static/thumbnails/sphx_glr_calendar_average_example.png
Yes, sorry I just put a placeholder there while I make a new one. All good points. 

I think the value of listing dependencies in markdown is linking documentation. We could move this to the end of the script, like a read more section after the example?

2023-02-28 19:42 UTC, jukent commented
Hi could you take another look at this now that I've incorporated @anissa111 's feedback.

2023-03-01 16:23 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "Then, we use xarray's [open_dataset](http://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html) function to read the data into an xarray dataset, choose a single model from the e
```suggestion
        "Then, we use xarray's [open_dataset](http://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html) function to read the data into an xarray dataset, choose a single model from the ensemble run, and extract its surface temperature data into `temp`."
```
Missing punctuation

2023-03-01 16:27 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "The plot output has adjusted datetimes instead of using integers to denote the day of the year for the time axis. The year for the outputted data is the floor of the median year of the input
> The plot output has adjusted datetimes instead of using integers to denote the day of the year for the time axis.

I'm a bit confused about this part since the plot has integers for the time axis. It looks like you're doing the conversion, but is isn't showing up properly in the figure 

Edit: It looks like this is an issue with a few different figures

![image](https://user-images.githubusercontent.com/42781301/222201822-e226441f-1618-4edb-8168-eb395338d8d2.png)

2023-03-01 16:33 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "daily = climatology_average(temp, 'day')\n",
You mention in the text above this cell that you are setting the `freq` argument to "daily". While we can use positional arguments here, can you change this for clarity?

```suggestion
        "daily = climatology_average(temp, freq='day')\n",
```

2023-03-01 16:34 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "Let's start with the daily climatology average. The following plot shows output of the raw data being aggregated using the `climatology_average` function with the `freq` argument set to 'dai
Typo

```suggestion
        "Let's start with the daily climatology average. The following plot shows output of the raw data being aggregated using the `climatology_average` function with the `freq` argument set to 'day'. "
```

2023-03-01 16:36 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "Next we'll compute the monthly climatology averages by using `climatology_average` with the `freq` argument set to `monthly`.\n",
Similar typo as above. The argument value is "month" rather than "monthly". This brings up an interesting thought though. Should `freq` take in the values "hourly", "daily", "monthly", and "seasonal" rather than the current "hour", "day", "month", "season" since it would be more intuitive and closer to natural speech? @anissa111 @jukent Thoughts?
```suggestion
        "Next we'll compute the monthly climatology averages by using `climatology_average` with the `freq` argument set to `month`.\n",
```

2023-03-01 16:38 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAj4AAAHFCAYAAADyj/PrAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAACIUElEQ
The images for daily and monthly climatologies look the same other than the title. Is this an error?

Daily:
![image](https://user-images.githubusercontent.com/42781301/222203796-1b053ced-cfcd-4da2-b842-4adb61aa83d5.png)

Monthly:
![image](https://user-images.githubusercontent.com/42781301/222203897-2056062c-e4a8-4ece-ad6d-b2f24d214de8.png)

2023-03-01 16:39 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "monthly = climatology_average(temp, 'month')\n",
Similar suggestion as seen above. I think we should use the name of the argument rather than using the positional option for clarity in example scripts. I can see an argument for going either way, but I think this will avoid any confusion.
```suggestion
        "monthly = climatology_average(temp, freq='month')\n",
```

2023-03-01 16:45 UTC, anissa111 commented on docs/examples/climatology_average.ipynb
> +        "Next we'll compute the monthly climatology averages by using `climatology_average` with the `freq` argument set to `monthly`.\n",
I'm not sure I have a strong opinion about this. I think I would err on the side of following what similar packages are using. Is there any precedent in scipy, astropy, xarray, or anything similar?

2023-03-01 16:49 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "Next we'll compute the monthly climatology averages by using `climatology_average` with the `freq` argument set to `monthly`.\n",
I don't think there is a precedent since I designed this functions to fill a need that wasn't being met by other packages. It wouldn't be too hard to add `monthly` as an alias for `month` with how the function already handles inputs. It might be a nice quality of life thing, but is low priority

2023-03-01 16:54 UTC, jukent commented on docs/examples/climatology_average.ipynb
> +        "Next we'll compute the monthly climatology averages by using `climatology_average` with the `freq` argument set to `monthly`.\n",
I think it's fine as is though. I just didn't notice that I had done it incorrectly because no errors or warnings were raised. Perhaps something should be raised if the frequency is set to a value the method doesn't know?

2023-03-01 17:36 UTC, anissa111 reviewed
This is looking really good! Thanks for incorporating my suggestions about moving away from an -examples style script. I've left a few small points below along with Heather's suggestions.

Additionally, this is a small point, but we could still include all three plots in the thumbnail like before even though we technically never plot them all together.

2023-03-01 19:26 UTC, jukent commented on docs/examples/climatology_average.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAj4AAAHFCAYAAADyj/PrAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAACIUElEQ
I found the problem. I'll push that and the subplot gallery card.

2023-03-01 19:26 UTC, jukent commented on docs/examples/climatology_average.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAj4AAAHFCAYAAADyj/PrAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAACIUElEQ
well the problem with the subplots but not with the x axis.

2023-03-01 19:35 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "Next we'll compute the monthly climatology averages by using `climatology_average` with the `freq` argument set to `monthly`.\n",
> I think it's fine as is though. I just didn't notice that I had done it incorrectly because no errors or warnings were raised. Perhaps something should be raised if the frequency is set to a value the method doesn't know?

You had the value set correctly in the function call but had a typo in the explanatory text. That kind of argument check does exists, but luckily you did things a-ok and didn't trigger it.

2023-03-01 19:36 UTC, hCraker commented on docs/examples/climatology_average.ipynb
> +        "import geocat.datafiles as gdf"
Ooo yes I like that. We have done that before in various tutorials and should probably do it here too

2023-03-01 19:52 UTC, jukent commented on docs/examples/climatology_average.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAj4AAAHFCAYAAADyj/PrAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAACIUElEQ
fixed the x-axis too. It was some script I dropped when removing gc-viz.

2023-03-01 20:00 UTC, jukent commented on docs/examples/climatology_average.ipynb
> +        "import geocat.datafiles as gdf"
Done

2023-03-01 20:05 UTC, jukent commented
Unrelated broken link:

`(    installation: line   49) broken    https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html - 404 Client Error: Not Found for url: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html`

2023-03-01 21:46 UTC, hCraker approved these changes
Thanks for adding this example!

2023-03-01 22:29 UTC, anissa111 approved these changes

2023-03-01 22:29 UTC, merged