add custom season method
NCAR/geocat-comp pull request #411
Opened 2023-05-11 21:48 UTC by jukent

## PR Summary
Adds custom season list as kwarg for `climatology_average`
Closes #198

## PR Checklist

**General**
- [ ] Make an issue if one doesn't already exist
- [ ] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [ ] Add a brief summary of changes to `docs/release-notes.rst`
- [ ] Add appropriate labels to this PR
- [ ] Make your changes in a forked repository rather than directly in this repo
- [ ] Open this PR as a draft if it is not ready for review
- [ ] Convert this PR from a draft to a full PR before requesting reviewers
- [ ] Request `@NCAR/geocat` for reviews
- [ ] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.

**Functionality**
- [ ] Function is in appropriate module file
- [ ] New function(s) intended for public API added to `src/geocat/comp/__init__.py` file

**Testing**
- [ ] Tests for function exists in associated module test file
- [ ] Tests cover all possible logical paths in your function

**Documentation**
- [ ] Docstrings have been added to all new functions ([Documentation Standards](https://geocat.ucar.edu/pages/contributing.html#422-documentation))
- [ ] Docstrings have updated with any function changes
- [ ] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [ ] User facing functions have been added to `docs/user_api/index.rst` under their module

2023-05-11 21:54 UTC, jukent commented
Target final dataset:
<img width="853" alt="Screen Shot 2023-05-11 at 3 50 57 PM" src="https://github.com/NCAR/geocat-comp/assets/46687291/d22dd95b-df32-4006-a315-bb7a00ef25bb">

vs what we currently have:
<img width="867" alt="Screen Shot 2023-05-11 at 3 50 37 PM" src="https://github.com/NCAR/geocat-comp/assets/46687291/9bfec390-b954-4044-8cd7-dacdeee9c285">

I have the values matching up, and am still wrestling with the Xarray dimension(?) name where it says SON instead of season. I'm not sure if we want to add a pandas season index/ if that means something specific to the typical seasons (will research this).

And one issue is that in order to get this values. I have to comment out this block of code borrowed from `month_to_season`:
```
                    # For this season, the last "mean" will be the value for Dec so we drop the last month
                    if season == 'DJF':
                        data_filter = data_filter.isel(
                            {time_dim: slice(None, -1)})
                    # For this season, the first "mean" will be the value for Jan so we drop the first month
                    elif season == 'NDJ':
                        data_filter = data_filter.isel(
                            {time_dim: slice(1, None)})
```
or else that values are off in DJF. I need to look at this math more and know if this is right to not implement (as in are we doing it correctly in the non-custom season version). Any thoughts on that @anissa111

2023-05-11 22:13 UTC, jukent commented
Didn't expect this to fail tests in test_climate_anomaly and test_climate_average. Will look into this tomorrow hopefully.

2023-05-11 22:35 UTC, anissa111 commented
@jukent I'm not sure I know enough about that to have any valuable thoughts right now. I think it could make sense that the two implementations are different enough that this version wouldn't need that block, but I'd want to understand the underlying reason why, does that make sense?

2023-05-11 23:03 UTC, jukent commented
Yeah that makes sense. I think when we want winter from one year, we have to deal with it being over the dateline. But when we want winter from all years, it doesn't matter if January is in this winter or the next. Like the grouping of December 22 of January 23 together.

There is still the very first and very last year that could be affected? And that causes the small discrepancy. My hunch is that since we're going through months first it isn't needed or wanted but I'll lay it out better tomorrow.

2023-05-16 14:43 UTC, jukent commented
Related to #313

2023-05-19 23:24 UTC, anissa111 requested changes
I'm a bit concerned with the logic flow as written as mentioned in a few of my comments below for a few reasons, some of which predate this PR

1. I am a little uncozy with the logic structure of 
``` python
if <this setting>:
    do all analysis
    return

if <next setting>:
    do all analysis
    return
```
2. This introduces some edge cases such as what happens if the user specifies custom seasons, but a frequency of anything other than 'season'
3. Apart from the general uncozy mentioned in (1), I think we could be making better use of the `custom_seasons` optional argument here. What if we used a default of `custom_seasons = ['DJF', 'MAM', 'JJA', 'SON']` and then performed the calculation for seasons in the same way instead of separating the season calculation into a "custom" or "default" section? I would think, ideally, the same calculations for custom season should also work for the standard, correct?
4. Seeing the code in this PR, I'm again not totally sure why you've changed some of the inputs to kwargs instead of just arguments. 

Anyway, sorry for the late review, let me know if you'd like a dedicated time for me to explain some of my questions/thinking on suggestions!

2023-05-19 23:24 UTC, anissa111 commented on src/geocat/comp/climatologies.py
> +                    )
I feel like there's a cleaner way of accomplishing this. Maybe something along the lines of 

```python
if custom_seasons:
    # check for all valid seasons
    if not all([s in season_pd for s in custom_seasons]):
        raise ValueError(...)
```

2023-05-19 23:24 UTC, anissa111 commented on src/geocat/comp/climatologies.py
> +                                coords=dict(season=custom_seasons))
It seems like we're making a lot of copies here, is there a way to do this more in-place  as well as vectorized to avoid looping here?

2023-05-19 23:47 UTC, jukent commented on src/geocat/comp/climatologies.py
> +        - `NDJ` : for a season of November, December, and January
Right now the user would have to enter ['JJA'] - I wanted to type it to accept a string or a list of strings but this seemed easier first.

2023-05-19 23:50 UTC, jukent commented on src/geocat/comp/climatologies.py
> +    seasons_pd = {
Honestly, because it was called that in the month_to_season fx. I can change it to `season_dict` which is more intuitive.

2023-05-19 23:51 UTC, jukent commented
2. If the user specifies custom seasons but daily climatoloty, currently the frequency trumps it and the user would get daily climatology. You're right to point that out though. I think that is the behavior we want, but maybe raise a warning to say that their custom seasons will be ignored.
3. Good points. We could do some analysis to see if Xarray's method is faster at all -- but that would work and sounds cleaner for sure.


I'll address your other points and make some edits on Monday.

2023-05-23 16:26 UTC, jukent commented on src/geocat/comp/climatologies.py
> +        - `NDJ` : for a season of November, December, and January
just added support for this. We just turn 'JJA' into ['JJA'] before analysis.

2023-05-23 16:27 UTC, jukent commented on src/geocat/comp/climatologies.py
> +                                coords=dict(season=custom_seasons))
Tbh this is probably the hardest part for me. My one thought is to make a helper function for what's in the for-loop and then call it using list comprehension. Does that sound like a good approach @anissa111 or do you have another idea?

2023-06-29 00:48 UTC, jukent commented
I spent some time trying to solve the error in the climate_anomaly test. The error seems to be in the line `anom = dset.groupby(f"{time_dim}.season") - clim` (line 199) in the climate_anomaly fx. It won't let me take the this difference: "TypeError: unsupported operand type(s) for -: 'int' and 'method'". I tried to trick it by doing groupby on the clim line as well, or groupby and mean or sum (even though there are only one value for each group) and got various error messages. Here `clim` is the method type. I've seen climate anomalies done exactly like this elsewhere online, and it worked before. I think something about artificing the seasonal groupby for `clim` and using Xarray's defaults for `dset` is cauisng the discrepancy. 

I think the easiest solution is to go back to using the default Xarray method when custom seasons aren't specified (instead of specifying them as the default list). I don't love this, but if we're not offering custom season support to climate_anomaly it should work.

Or I could try to add custom_seasons to climate_anomaly, and do a "manual" groupby here as well.

There are other options, but these are what is coming to me right now.

2023-06-29 20:22 UTC, jukent commented
Passing local tests!

2023-07-07 19:55 UTC, anissa111 reviewed
Mostly just comments from this morning's meeting. I did manage to write something that might be a little more readable for that one section I said I'd take a stab at.

2023-07-07 19:55 UTC, anissa111 commented on geocat/comp/climatologies.py
>          )
I think it'd be good to propagate this update to the rest of `climatologies.py`

2023-07-07 19:55 UTC, anissa111 commented on geocat/comp/climatologies.py
> +
```suggestion
    attrs = {}
    if keep_attrs in {True, None}:
        attrs = dset.attrs
```
As discussed, we may want to implement a more universal helper function to handle this, but for now, I think this change will reduce unintended results.

2023-07-07 19:55 UTC, anissa111 commented on geocat/comp/climatologies.py
> +            custom_seasons = ['DJF', 'JJA', 'MAM', 'SON']
This is picky, but I think this might actually make more sense the other way around. To me, it seems counterintuitive to proceed with a variable named `custom_seasons`, even if the default seasons are being used.

I would suggest something like:
```python
seasons = ['DJF', 'JJA', 'MAM', 'SON']
if custom_seasons:
    ...
    seasons = custom_seasons
```

2023-07-07 19:55 UTC, anissa111 commented on geocat/comp/climatologies.py
> +            if type(custom_seasons) == str:
```suggestion
            if isinstance(custom_seasons, str):
```

2023-07-07 19:55 UTC, anissa111 commented on geocat/comp/climatologies.py
> +                )
As you saw this morning, I think we can improve the readability on this particular section. 

```suggestion
            invalid_seasons = [s for s in custom_seasons if s not in seasons_dict]
            if invalid_seasons:
                raise ValueError(
                    f"contributed: climatology_average: bad season(s): {invalid_seasons}. Valid seasons include: {list(seasons_dict.keys())}"
                )
```

2023-07-07 19:55 UTC, anissa111 commented on test/test_climatologies.py
> +            'season': np.array(season_clim_time).astype(object),
Wait, sorry if I missed something, but why is the trailing `.astype(object)` needed here?

2023-07-07 20:11 UTC, jukent commented on geocat/comp/climatologies.py
> +                )
This is much better, thanks

2023-07-07 20:17 UTC, jukent commented on geocat/comp/climatologies.py
>          )
Done. Updated the tests too.

2023-07-07 20:17 UTC, jukent commented on geocat/comp/climatologies.py
> +            custom_seasons = ['DJF', 'JJA', 'MAM', 'SON']
Makes sense to me.

2023-07-07 20:19 UTC, jukent commented on test/test_climatologies.py
> +            'season': np.array(season_clim_time).astype(object),
Because otherwise you get type "<U3" as opposed to "object" for each season, which is pretty minor except it makes out output deviate from what it used to be and from what Xarray's is.

2023-07-07 20:20 UTC, jukent commented on test/test_climatologies.py
> +            'season': np.array(season_clim_time).astype(object),
I changed it in line 604 of climatology, and had to change it in the tests too for the result to match.

2023-07-07 20:20 UTC, anissa111 commented on test/test_climatologies.py
> +            'season': np.array(season_clim_time).astype(object),
Oh right, okay!

2023-07-07 20:24 UTC, anissa111 commented on geocat/comp/climatologies.py
> +        custom_seasons: list = None,
Whoops sorry missed this one. The typing should match the docstring.
```suggestion
        custom_seasons: typing.Union[list, str] = None,
```

2023-07-07 20:25 UTC, jukent commented on geocat/comp/climatologies.py
> +        custom_seasons: list = None,
Good catch!

2023-07-07 20:41 UTC, anissa111 approved these changes
This should be good to go when the tests finish! Good job!!

2023-07-07 21:17 UTC, merged