Contributor's Guide
NCAR/geocat-comp pull request #450
Opened 2023-09-06 17:13 UTC by anissa111

## PR Summary

Closes #440 

Summary of changes:
- adds a contributor's guide to the documentation
- links the new contributor's guide in CONTRIBUTING.md

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [ ] Add a brief summary of changes to `docs/release-notes.rst`
- [x] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo 
- [ ] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.

2023-09-06 18:24 UTC, jukent approved these changes
Thanks for all your hard work improving this documentation. There is a lot here so I could have missed a spellcheck or something and I'm sure as we use the document we might find areas for it to grow in - but let's merge these changes so we can get started :)

2023-09-06 21:34 UTC, kafitzgerald commented on docs/contrib.rst
> +Discussions <https://github.com/NCAR/geocat-comp/discussions>`__ You can also
```suggestion
Discussions <https://github.com/NCAR/geocat-comp/discussions>`__. You can also
```

2023-09-06 21:48 UTC, kafitzgerald requested changes
Looks good overall!  Just caught some minor typos.

2023-09-06 21:48 UTC, kafitzgerald commented on docs/contrib.rst
> +on! We recomment working with core developers to implement new functionality. We
```suggestion
on! We recommend working with core developers to implement new functionality. We
```

2023-09-06 21:48 UTC, kafitzgerald commented on docs/contrib.rst
> +    conda create -c conda-forge -n geocat_comp_build python=3.10
do we want to explicitly specify 3.10?

2023-09-06 21:48 UTC, kafitzgerald commented on docs/contrib.rst
> +may provide feedbac like asking for changes or suggesting improvements. You can
```suggestion
may provide feedback like asking for changes or suggesting improvements. You can
```

2023-09-06 22:02 UTC, anissa111 commented on docs/contrib.rst
> +    conda create -c conda-forge -n geocat_comp_build python=3.10
I went back and forth on this. I ended up specifying 3.10 because that's what xarray does and because I wanted to show the "recommended" way to specify a python version with a environment file that has a range of acceptable versions.

2023-09-06 22:04 UTC, anissa111 commented
> Looks good overall! Just caught some minor typos.

Haha I really thought I had spell check enabled on my IDE, I'll have to go back and fix that.

2023-09-06 22:05 UTC, kafitzgerald approved these changes

2023-09-06 22:06 UTC, erogluorhan reviewed
Thanks very much for this! I have a few inline comments

2023-09-06 22:06 UTC, erogluorhan commented on docs/contrib.rst
> +**************
Additionally, if we were to still have a "where to start" section, it'd mention deciding the way of contribution, and having a GitHub account (i.e. hosting "Git and Github" section under "Where to start"?); in other words basics of contribution.

2023-09-06 22:06 UTC, erogluorhan commented on docs/contrib.rst
> +Get the code
I'd recommend to use the same phrase both here and in the above list (i.e. "Fork the ``geocat-comp`` repository on GitHub." for increased readability and easier mapping). This applies to almost each of below sections as well.

2023-09-07 18:24 UTC, anissa111 commented on docs/contrib.rst
> +**************
I agree that the flow is a little funny.

Could you expand on what you mean by seeing the different ways of contributing throughout the documentation?

2023-09-07 18:29 UTC, anissa111 commented on docs/contrib.rst
> +Get the code
I went back and forth on this. I ended up writing it like this because some steps did not need a lot of additional explanation, but I definitely agree about your mapping point. 

I'm going to more closely align the phrasing and include links to their corresponding sections

2023-09-07 19:36 UTC, erogluorhan commented on docs/contrib.rst
> +**************
Yeah, after the "Introduction" mentions those many ways, "Where to start" would preferably come next and mention the need for deciding how to contribute and the necessity of a GitHub account for any one of these contributions (i.e. the "Git and GitHub" section here) etc. After that, something like this structure would be easier to read:

1. Reporting bugs
   <short paragraph>
2. Requesting new or additional functionality
   <short paragraph>
3. Improving our documentation
   Not sure; maybe a short paragraph or this would also require a workflow similar to "Contributing your own code"
4. Contributing your own code
   <Some text> then 
   4.1. Development worflow
   ...

2023-09-08 16:36 UTC, anissa111 commented on docs/contrib.rst
> +**************
Okay, I've re-arranged some stuff that more closely aligns with your suggested structure. I actually couldn't nest that deeply. but I've added a "Improving Documentation" section at the top with the bug/feature request sections that links to the lower docs section and moved the development workflow subsections up to top-level visibility so they can be navigated without having to scroll into the section to see them

2023-09-08 16:38 UTC, anissa111 commented on docs/contrib.rst
> +Get the code
Done! There's still a section that doesn't correspond to a later section (wait for PR to be merged) and another (make and check docs) that links to two sections, but I've included internal links to all the relevant subsequent sections to the overview section, which should make finding the longer instructions way more straightforward.

2023-09-08 17:36 UTC, erogluorhan commented on docs/contrib.rst
> +**************
Looks great; thank you!

2023-09-08 17:37 UTC, erogluorhan commented on docs/contrib.rst
> +Get the code
Great now; thanks!

2023-09-08 17:37 UTC, erogluorhan approved these changes
Thanks very much for putting this together!

2023-09-08 18:29 UTC, merged