Convert unittest to pytest
NCAR/geocat-comp pull request #478
Opened 2023-09-21 21:16 UTC by cyschneck

## PR Summary

Closes #462

## PR Checklist

**General**
- [ ] Make an issue if one doesn't already exist
- [ ] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [ ] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated
- [ ] Add appropriate labels to this PR
- [ ] Make your changes in a forked repository rather than directly in this repo
- [ ] Open this PR as a draft if it is not ready for review
- [ ] Convert this PR from a draft to a full PR before requesting reviewers
- [ ] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.
- [ ] If needed, squash and merge PR commits into a single commit to clean up commit history

**Functionality**
- [ ] Function is in appropriate module file
- [ ] New function(s) intended for public API added to `geocat/comp/__init__.py` file

**Testing**
- [ ] Tests for function exists in associated module test file
- [ ] Tests cover all possible logical paths in your function

**Documentation**
- [ ] Docstrings have been added to all new functions ([Documentation Standards](https://geocat-comp.readthedocs.io/en/stable/contrib.html#docstrings))
- [ ] Docstrings have updated with any function changes
- [ ] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [ ] User facing functions have been added to `docs/user_api/index.rst` under their module

**Examples**
- [ ] Any new notebook examples added to `docs/examples/` folder
- [ ] Pre-run all notebook cells
- [ ] New notebook files added to `docs/examples.rst` toctree
- [ ] New notebook files added to new entry in `docs/gallery.yml` with appropriate thumbnail photo in `docs/_static/thumbnails/`

2023-09-22 17:53 UTC, cyschneck commented
Original testing output:
```
```
Converted to pytest output:
```
```
Warnings will be addressed as part of #477

2023-09-22 20:29 UTC, anissa111 requested changes
This is good! I've left a few comments below. Also, I think we should be able to remove the `flags: unittests` line in `.github/workflows/ci.yml` since everything should be pure pytest now.

2023-09-22 20:29 UTC, anissa111 commented on test/test_gradient.py
> +    def test_setUpClass(cls) -> None:
This should probably be converted to a `@pytest.fixture()` instead. It's not a test itself exactly and I beleive that `@pytest.fixture()` is the pytest method for doing a `@classmethod` set up class.

I was originally going through and commenting on each occurence, but it got really repetitive. For brevity, I'll just add this one and note that I think they should be changed for our entire test suite.

2023-09-22 20:29 UTC, anissa111 commented on test/test_meteorology.py
> +
I think `@pytest.fixture()` includes both set up and tear down, woth setup occuring before a `yeild` statement and teardown statements after.

Also, I'm not going to make comments everywhere for this, but I think we should use `@pytest.fixture()`s everywhere for both set up and tear down

2023-09-22 20:29 UTC, anissa111 commented on test/test_stats.py
While we're at it, I think we should see if we can `BaseEOFTestCase` to a `@pytest.fixture()`, too.

2023-09-22 20:41 UTC, cyschneck commented on test/test_gradient.py
> +    def test_setUpClass(cls) -> None:
I'll go through and add this change now, thanks!

2023-09-25 18:58 UTC, cyschneck commented on test/test_stats.py
What test is BaseEOFTestCase part of? I don't see it in the repo

2023-09-25 20:42 UTC, anissa111 commented on test/test_stats.py
Oh sorry, I meant `BaseEOFTestClass`. It's in this file, `test_stats.py`

2023-09-25 21:05 UTC, cyschneck commented on test/test_stats.py
There isn't currently support for class fixtures (`ValueError: class fixtures not supported (maybe in the future)`). `test_stats.py` runs with `BaseEOFTestClass`, but I could see about rewriting it, is there an advantage to setting it to a pytest fixture?

2023-09-25 21:09 UTC, cyschneck commented
[x] removed the `flags: unittests` line in `.github/workflows/ci.yml`
[x] removed `#from unittest import TestCase` from test/test_stats.py
[x] converted `classmethod` to `pytest.fixtures()` (for `setupClass()`)
[x] Remove `closeClient` function, replaced with `yield` to close client

2023-09-25 21:40 UTC, anissa111 commented on test/test_stats.py
I mostly just thought it would standardize our set up a bit more, but since it isn't supported I think it's fine to leave it.

2023-09-27 21:17 UTC, anissa111 reviewed
In summary from our convo:
- fixtures that just create class variables can likely be eliminated by just creating these variables in the class
- fixtures that read in data from files should be kept and provide these variables with return or yield instead of assigning to the class
- set ups with dask client creation should be pulled into their own fixtures and only provided to the tests that require them instead of lumping them in with an `autouse=True` fixture.

Additionally, where possible I think we should use more descriptive function names for these fixtures where possible.

2023-10-03 20:04 UTC, cyschneck commented
Improved runtime from 240s -> 140s with new fixtures
```
========================= 251 passed, 41 warnings in 140.58s (0:04:00) ==========================
```

2023-10-05 20:35 UTC, cyschneck commented
Further fixtures for files I/O continue to improve runtime (from 140s -> 135s) from the original 240s
```
========================= 251 passed, 41 warnings in 135.87s (0:02:15) ==========================
```

2023-10-07 01:30 UTC, anissa111 commented
I've made a [branch off of this one](https://github.com/cyschneck/geocat-comp/compare/convert_unittest...anissa111:geocat-comp:issue478_cora) that shows the type of changes I'm looking for on `test/test_gradient.py` and `test/test_meteorology.py`.

My formatter took over and made some additional changes, but I hope it's still possible to see the substantive changes over the formatting differences.

2023-10-24 23:02 UTC, anissa111 reviewed
Thanks for the changes! I've included one last request here and then I think we'll be good to go.

2023-10-24 23:02 UTC, anissa111 commented on test/test_interpolation.py
> +        return test_output['mask']
I think we can reduce the number of fixtures here. Unlike in other places where the slicing is non-obvious and creating named fixtures improved readability, here the fixtures are largely just named after the index and variable, which we could access directly from tests. Since these fixtures request all the original `test_input` and `test_output`, separating them shouldn't give us any significant performance improvements.

2023-10-25 21:55 UTC, anissa111 approved these changes
Looks good, thanks for that last change! This should be good to merge after #495 to clear the link check failure!

2023-10-25 21:58 UTC, anissa111 commented
Oh! Also just noting that this should be moved to the next release section of `docs/release-notes.rst`, but that can be handled with the merge conflicts if you'd prefer

2023-10-26 16:50 UTC, merged