Private API Xarray: dataArray -> dataArray.variable
NCAR/geocat-comp pull request #492
Opened 2023-10-20 21:15 UTC by cyschneck

## PR Summary

Closes #381

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [x] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated
- [ ] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo
- [x] Open this PR as a draft if it is not ready for review
- [ ] Convert this PR from a draft to a full PR before requesting reviewers
- [x] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.
- [x] If needed, squash and merge PR commits into a single commit to clean up commit history

2023-10-24 21:41 UTC, cyschneck commented
Test errors appear to arise in most recent xarray (2023.10.1) interaction with existing tests

`/xarray/core/dataarray.py:869: in __setitem__`
```
self.variable[key] = value
```
Calls: `/xarray/core/variable.py:880: in __setitem__`
```
value = value.set_dims(dims).data
```
Throws: `ValueError: new dimensions ('sigma',) must be a superset of existing dimensions ('dim_0',)`

2023-11-01 17:05 UTC, cyschneck commented
Current test failure: [`test/test_climatologies.py::Test_Month_to_Season::test_month_to_season_custom_time_coordinate[ds4-dataset1-None-Tair-expected1:350`](https://github.com/NCAR/geocat-comp/blob/cf476447a8b3893bade867e0d3e69ad80200e557/test/test_climatologies.py#L350C8-L350C8)

Throws the error `ValueError: unit abbreviation w/o a number`, but the actual issue is `loffset` in [climatologies.py:303](https://github.com/NCAR/geocat-comp/blob/cf476447a8b3893bade867e0d3e69ad80200e557/geocat/comp/climatologies.py#L303C5-L305C49) when xarray resample is called

```
means = data_filter.resample({time_coord_name: quarter}, loffset='MS').mean(keep_attrs=keep_attrs)
```

ValueError originates in xarray [`resample_cftime.py:155`](https://github.com/pydata/xarray/blob/fcdc81028bd3c066fc7c9fbf965d2c66fcf8da4c/xarray/core/resample_cftime.py#L155) where xarray calls pandas to_timedelta with `loffset`

```
labels = labels + pd.to_timedelta(self.loffset)
```

`loffset` is accepted since `CFTimeGrouper:first_items` expected `loffset` to be a a string, datetime.timedelta, or instance of a BaseCFTimeOffset. As a string, `loffset="MS" with pandas function ``pd.to_timedelta("MS")`. However, [pandas has dropped `loffset` string support since pandas version 1.1.0](https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.DataFrame.resample.html). The ValueError being thrown is a deceptive error due to when pandas attempts to convert the loffset "MS" to a timedelta, but as loffset is deprecated within pandas when "MS" is attempted to be [converted to TimeDelta without units](https://github.com/pandas-dev/pandas/blob/eedf0d5cc2801cc3849ec9abb4e8b3f509d91ee9/pandas/core/tools/timedeltas.py#L222)

```
result = Timedelta(r="MS", unit=None)
```

It throws an invalid ValueError. As an invalid Timedelta string, the error can be replicated as `pandas.to_timedelta("MS")`

```
>>> import pandas as pd
>>> pd.to_timedelta("MS")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/geocat_comp_build/lib/python3.11/site-packages/pandas/core/tools/timedeltas.py", line 223, in to_timedelta
    return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/geocat_comp_build/lib/python3.11/site-packages/pandas/core/tools/timedeltas.py", line 233, in _coerce_scalar_to_timedelta_type
    result = Timedelta(r, unit)
             ^^^^^^^^^^^^^^^^^^
  File "timedeltas.pyx", line 1820, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "timedeltas.pyx", line 653, in pandas._libs.tslibs.timedeltas.parse_timedelta_string
ValueError: unit abbreviation w/o a number
```

The current issue appears to arise as a result of xarray not entirely deprecating loffset (as of version 2023.10.1) so invalid arguments are internally passed to pandas (as of version 2.1.2) which has deprecated loffset

2023-11-01 19:25 UTC, kafitzgerald commented
Looks like handling of the time offset arithmetic is different for cftime. 

Probably why `xr.coding.cftime_offsets.to_offset` exists (though this is also private API).

2023-11-01 19:45 UTC, kafitzgerald commented
> The current issue appears to arise as a result of xarray not entirely deprecating loffset (as of version 2023.10.1 with https://github.com/pydata/xarray/pull/7444) so invalid arguments are internally passed to pandas (as of version 2.1.2) which has deprecated loffset

I think this is a little more nuanced. 

The xarray fix to postpone the deprecation of the loffset argument should still work for most cases, but [a later PR introduced a line](https://github.com/pydata/xarray/pull/7206/files#diff-71ee1ab3258dca8894ad22fd08ff181e140262a5ac38985d49ee0a6ee6039319R155) that converts the loffset argument to a pandas timedelta (via pd.to_timedelta) and that fails since "MS" is invalid input.  

Unfortunately, this means that the xarray resample/loffset fix no longer works for us and as mentioned above and shown in the CI failures the time offset arithmetic is a little more complicated in this case.

2023-11-02 17:18 UTC, jukent approved these changes

2023-11-02 20:00 UTC, anissa111 requested changes
Don't forget the pin in `setup.cfg`!

2023-11-02 20:05 UTC, kafitzgerald commented
Having missed some version pins myself recently...  I think this version pin is also in some additional *.yml files and the requirements.txt in addition to the setup.cfg

2023-11-03 17:30 UTC, cyschneck commented
The changes to `interpolation.py` are to [fix the issue with the interpolation tests throwing](https://github.com/NCAR/geocat-comp/pull/492#issuecomment-1778087254) 

```
ValueError: new dimensions ('sigma',) must be a superset of existing dimensions ('dim_0',)
```

2023-11-03 18:09 UTC, kafitzgerald requested changes
The changes here all look reasonable to me (introducing more private API from xarray is non-ideal, but should be less of a risk with expanded upstream testing and hopefully we do something different in the long run).    

I do think we should better document the change in interpolation.py and the loffset change.  At least including them in the PR description and changing the title and release notes blurb to something more inclusive of the changes here.  

Probably a good idea to open another issue about Xarray private API as well since we'll be introducing more rather than removing it.  

Will be nice to see this get merged though!

2023-11-03 18:25 UTC, cyschneck commented on geocat/comp/interpolation.py
> +                                          dims=[lev_dim])
Will do!

2023-11-03 19:43 UTC, cyschneck commented on geocat/comp/climatologies.py
> +        )
I added a write up in a backlog Issue #508

2023-11-03 20:19 UTC, kafitzgerald commented on docs/release-notes.rst
> +* Unpin xarray in enviroment builds with changes to interpolation.py (specify dims in xr.DataArray) and climatologies.py (replace loffset with to_offset) by `Cora Schneck`_ in (:pr:`381`)
I think this still needs to get bumped up to a v2023.11.0 (unreleased) section.  

Otherwise, things look good to me!

2023-11-08 16:42 UTC, kafitzgerald approved these changes
Looks good!

2023-11-10 20:46 UTC, anissa111 approved these changes
Sorry, I missed the re-review request, this looks good!

2023-11-10 20:46 UTC, merged