New NSF NCAR Branding
NCAR/geocat-comp pull request #541
Opened 2024-01-23 19:09 UTC by cyschneck

## PR Summary

Closes #540

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [ ] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated
- [x] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo
- [x] Open this PR as a draft if it is not ready for review
- [ ] Convert this PR from a draft to a full PR before requesting reviewers
- [ ] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.
- [ ] If needed, squash and merge PR commits into a single commit to clean up commit history

2024-01-23 22:20 UTC, cyschneck commented
readthedocs has already been updated to include the new NSF logo, these changes add NSF the few remaining instances in the text

I was fixing some Linux issues on my end so when I committed the changes to release-notes and it appears to have duplicated the original commit for some reason, either way, the changes don't conflict

2024-01-23 22:49 UTC, anissa111 requested changes
We should also update [docs/index.rst](https://github.com/NCAR/geocat-comp/blob/1f14139bd63e746aa1cb229d8a6ee8d071cfbaa6/docs/index.rst#L15) (line 15) and [docs/conf.py](https://github.com/NCAR/geocat-comp/blob/1f14139bd63e746aa1cb229d8a6ee8d071cfbaa6/docs/conf.py#L258)

Also, don't forget to include this in `docs/release-notes.rst`!

2024-01-23 22:51 UTC, cyschneck commented on CODE_OF_CONDUCT.md
> +Instances of unacceptable behavior can be brought to the attention of the project administrator(s) who may take any action as outlined in the Consequences section below. However, making a report to a
No changes needed on the text side of things?

2024-01-23 22:58 UTC, kafitzgerald commented on CODE_OF_CONDUCT.md
The UCAR Codes of Conduct where this came from live here: https://www.ucar.edu/who-we-are/ethics-integrity/codes-conduct

2024-01-23 23:12 UTC, kafitzgerald requested changes
Thanks for doing this!

2024-01-23 23:12 UTC, kafitzgerald commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607349.**
```suggestion
    Boulder, CO, USA: UCAR/NSF NCAR - Computational and Information Systems Lab. doi:10.5281/zenodo.6607349.**
```

2024-01-23 23:12 UTC, kafitzgerald commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:\<DOI\>.**
```suggestion
    Boulder, CO, USA: UCAR/NSF NCAR - Computational and Information Systems Lab. doi:\<DOI\>.**
```

2024-01-23 23:12 UTC, kafitzgerald commented on docs/citation.rst
> +    Boulder, CO: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607205.**
```suggestion
    Boulder, CO: UCAR/NSF NCAR - Computational and Information Systems Lab. doi:10.5281/zenodo.6607205.**
```

2024-01-23 23:12 UTC, kafitzgerald commented on CODE_OF_CONDUCT.md
It looks like it's all UCAR so no change needed.

2024-01-23 23:13 UTC, kafitzgerald commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607349.**
I realize the lab name typo is from before, but we might as well fix it.

2024-01-23 23:14 UTC, anissa111 commented on CODE_OF_CONDUCT.md
> +Instances of unacceptable behavior can be brought to the attention of the project administrator(s) who may take any action as outlined in the Consequences section below. However, making a report to a
I don't think so, but I'd check the source we pulled this from to see what they've done, I think @kafitzgerald linked it below somewhere

2024-01-23 23:15 UTC, anissa111 commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607349.**
Actually, might this actually supposed to be UCAR/NSF NCAR?

2024-01-23 23:55 UTC, kafitzgerald commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607349.**
Is that not in the suggestion as well?  

It does look like they don't love slashes in the new guidelines either (just looked again).  Given that CISL is part of NSF NCAR, I think `NSF NCAR Computational and Information Systems Lab` is probably what this should be.

Last I looked, VAST is Visualization and Analysis Software and Technology as well and not what we have here.  I think that part is in the DOI metadata though as well and should probably be addressed separately.

Sorry for the sidebar here.

2024-01-24 04:58 UTC, anissa111 commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607349.**
Oh gosh, yeah, you're right sorry I was reading the suggested change incorrectly 👍

2024-01-24 20:12 UTC, cyschneck commented on CODE_OF_CONDUCT.md
Updated to remove the UCAR parts

2024-01-24 20:12 UTC, cyschneck commented on docs/citation.rst
> +    Boulder, CO, USA: NSF UCAR/NCAR - Computational and Informational System Lab. doi:10.5281/zenodo.6607349.**
`NSF NCAR Computational and Information Systems Lab` seems right based on the branding details

2024-01-24 22:21 UTC, anissa111 requested changes
We still need to make a change here: https://github.com/NCAR/geocat-comp/blob/1f14139bd63e746aa1cb229d8a6ee8d071cfbaa6/docs/conf.py#L258

2024-01-24 22:21 UTC, anissa111 commented on docs/index.rst
> +              ncar command language, national center for atmospheric research,
```suggestion
              ncar command language, nsf national center for atmospheric research,
```

I think we need to change this, as well [according to the branding guidance](https://sundog.ucar.edu/page/7480)

2024-01-24 22:29 UTC, cyschneck commented on docs/index.rst
> +              ncar command language, national center for atmospheric research,
Yep, good catch

2024-01-25 17:54 UTC, kafitzgerald reviewed
Looks good to me!

I did reach out to design yesterday to double check on the logos after a quick conversation w/ Orhan about the same thing on a different repo.  Apparently the NSF/GeoCAT logo (https://github.com/NCAR/geocat-comp/blob/main/docs/_static/images/logos/GeoCAT_nsf.svg) we have in the upper left hand corner of the docs (and maybe elsewhere) does need to get replaced.  Sorry if I suggested otherwise.  

The recommendation from design was to use the [new NSF NCAR logo displayed on the Sundog page](https://sundog.ucar.edu/page/7480#Interim-Guidance-on--11) instead.

Let me know if you'd like me to make that change.

2024-01-25 19:33 UTC, cyschneck commented
I don't see anything in the branding information about crediting NSF as the docs do in via the [nsf.png](https://github.com/NCAR/geocat-comp/blob/main/docs/_static/images/logos/nsf.png), so can this one remain the same?

2024-01-25 21:20 UTC, kafitzgerald approved these changes

2024-01-29 16:24 UTC, anissa111 approved these changes

2024-01-29 19:21 UTC, merged