Dewtemp
NCAR/geocat-comp pull request #95
Opened 2021-01-04 18:20 UTC by anissa111

Addresses #94 

This is currently a work in progress as dask and xarray support is added for the purpose of supporting S@S efforts.

Summary:
- implementation of dewtemp
- basic testing added using ground truth from ncl
- support for numpy

2021-01-25 18:40 UTC, erogluorhan requested changes
The code looks good to me, and I can confirm tests are passing. Please address a few inline comments.

2021-01-25 18:40 UTC, erogluorhan commented on src/geocat/comp/dewtemp_trh.py
> +    """ This function calculates the dew point temperature given temperature and relative humidity
For docstrings, I would suggest using the format (i.e. indentation, keywords such as Args and Return, etc.) from geocat-f2py (e.g. dpres_plevel_wrapper.py) because it was decided to be most favorable based on an investigation.

2021-01-25 18:40 UTC, erogluorhan commented on test/test_dewtemp_trh.py
> +class Ttest_relhum(unittest.TestCase):
Please add two extra test cases:
1) An additional array-run-test that tests for Xarray inputs rather than Numpy.
2) An additional array-run-test that tests for an already-chunked array. It may be a Dask array because you seem to already be converting Numpy inputs to first Xarray then Dask array.

2021-01-25 18:40 UTC, erogluorhan commented on src/geocat/comp/dewtemp_trh.py
> +    tdk = map_blocks(_dewtemp, temperature, relative_humidity)
My understanding from this entire function is that if the input is Numpy, the code is converting it to first an Xarray, and then to an auto-chunked Dask array. However, if it is an Xarray (either chunked or unchunked), then it does not perform any chunking or conversion to Dask array. Alternatively, the code seems to be capable of taking inputs as already chunked Dask arrays, but this is not documented. So, please test those Xarray and Dask input cases in unit tests (for which I have already put a comment below), and document input alternatives accordingly in the docstrings.

2021-02-11 18:41 UTC, erogluorhan reviewed
Looks great overall; please address a few inline comments, and then we are done

2021-02-11 18:41 UTC, erogluorhan commented on src/geocat/comp/dewtemp.py
> +def dewtemp_trh(temperature, relative_humidity):
What purpose is this alias for? Can't we choose either name and go with that one in the user API?

2021-02-11 18:41 UTC, erogluorhan commented on src/geocat/comp/dewtemp.py
> +    """ This function calculates the dew point temperature given temperature and relative humidity
I am not sure if we need this docstrings, which is very close to that of the user API function other than argument names.

2021-02-11 18:41 UTC, erogluorhan commented on src/geocat/comp/dewtemp.py
> +    """ This function calculates the dew point temperature given temperature and relative humidity
I am sorry to realize it now but I misled you to this docstrings format. The format of our preference is the Google format, which would make this docstrings look like (It is not any issue but would be better to be consistent with one format of choice and apply it to our new PRs like here):

```
"""
    This function calculates the dew point temperature given temperature and relative humidity
    using equations from John Dutton's "Ceaseless Wind" (pp 273-274)

    Parameters
    ----------

    temperature : :class:`numpy.ndarray`, :class:`xr.DataArray`, :obj:`list`, or :obj:`float`:
        Temperature in K

    relative_humidity : :class:`numpy.ndarray`, :class:`xr.DataArray`, :obj:`list`, or :obj:`float`:
        Relative humidity. Must be the same dimensions as temperature


    Returns
    -------

    dew_pnt_temp : :class:`numpy.ndarray` or :obj:`float`:
        Dewpoint temperature in Kelvin. Same size as input variable temperature
"""
```

2021-02-11 18:52 UTC, andersy005 commented on src/geocat/comp/dewtemp.py
> +    dew_pnt_temp = dew_pnt_temp.compute()
👋🏽  @anissa111, I have a couple questions/comments:

1) Does this computation have to be done via dask? I'm imagining scenarios in which the user provides in-memory numpy arrays and their computations are routed through dask (which adds some performance overhead). They (user) will end up paying a price for using dask even when they don't want to use dask. 

2) It's my understanding that computation in `_dewtemp` consists of array elementwise operations and not blockwise (chunk) operations. I'm wondering whether the `map_blocks()` approach is needed here?

2021-02-11 19:24 UTC, andersy005 commented on src/geocat/comp/dewtemp.py
> +
The docstring mentions that this function supports `xarray.DataArray`. However, this check appears not to handle xarray.DataArray objects correctly. xarray is more flexible than numpy when it comes to the shapes of arrays since it uses labelled axes instead of the plain location of the axis in the array. 

For instance, consider these two dataarrays of shapes `(3, 2)` and `(2, 3)`:


```python
In [1]: import xarray as xr

In [2]: import numpy as np

In [3]: a = xr.DataArray(np.ones(6).reshape(2, 3), dims=['lat', 'lon'])

In [4]: a
Out[4]:
<xarray.DataArray (lat: 2, lon: 3)>
array([[1., 1., 1.],
       [1., 1., 1.]])
Dimensions without coordinates: lat, lon

In [5]: b = a.transpose()

In [6]: b
Out[6]:
<xarray.DataArray (lon: 3, lat: 2)>
array([[1., 1.],
       [1., 1.],
       [1., 1.]])
Dimensions without coordinates: lon, lat

In [7]: b.shape
Out[7]: (3, 2)

In [9]: a.shape
Out[9]: (2, 3)
``` 


- Adding these two arrays (elementwise) provides the correct result since xarray is used the `lat` and `lon` axis labels to figure out whether the two arrays are compatible via the broadcasting rules:

```python
In [12]: a + b
Out[12]:
<xarray.DataArray (lat: 2, lon: 3)>
array([[2., 2., 2.],
       [2., 2., 2.]])
Dimensions without coordinates: lat, lon
```

- On the other hand, numpy fails because it only cares about the location of an axis in an array:
- 
```python
In [13]: a.data + b.data
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-1892839ecaba> in <module>
----> 1 a.data + b.data

ValueError: operands could not be broadcast together with shapes (2,3) (3,2)
```

I think that for xarray, this check should check whether the input arrays are [_broadcastable_](https://numpy.org/doc/stable/reference/ufuncs.html#broadcasting) or just try using the `xr.broadcast()` function to broadcast the two arrays against one other:

```python

In [17]: xr.broadcast(a, b)
Out[17]:
(<xarray.DataArray (lat: 2, lon: 3)>
 array([[1., 1., 1.],
        [1., 1., 1.]])
 Dimensions without coordinates: lat, lon,
 <xarray.DataArray (lat: 2, lon: 3)>
 array([[1., 1., 1.],
        [1., 1., 1.]])
 Dimensions without coordinates: lat, lon)
```

2021-02-11 19:34 UTC, andersy005 commented on src/geocat/comp/dewtemp.py
> +    """ This function calculates the dew point temperature given temperature and relative humidity
Presuming you are using the [numpydoc docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html), I don't think the `:class:`, `:obj:` are needed:


- :class:`numpy.ndarray` - > numpy.ndarray
- :class:`xr.DataArray` -> xr.DataArray
- :obj:`list` -> list

etc....

2021-02-11 19:40 UTC, andersy005 commented on src/geocat/comp/dewtemp.py
> +    """ This function calculates the dew point temperature given temperature and relative humidity
Also, according to https://www.python.org/dev/peps/pep-0257/, the indentation in https://github.com/NCAR/geocat-comp/pull/95#discussion_r574738745 shouldn't be there:

```python
"""Compute ..... 

Function to compute .... 
..... 

Parameters
---------
....

Returns
-------
....

"""

```

2021-02-11 20:59 UTC, pilotchute approved these changes
I think that once the other reviewer's comments are addressed, that this will be good to go. One stamp of approval.

2021-02-11 23:29 UTC, pilotchute commented on src/geocat/comp/dewtemp.py
> +    dew_pnt_temp = dew_pnt_temp.compute()
My understanding that without using dask, the elementwise operations will only use a single core, while the data could be chunked to allow for elementwise ops to happen in parallel.

2021-02-12 01:26 UTC, anissa111 commented on src/geocat/comp/dewtemp.py
> +    """ This function calculates the dew point temperature given temperature and relative humidity
Anderson, you are totally right about all of the above. The docstring format was copied from elsewhere internally, and unifying them will be handled after the first release.

2021-02-12 08:16 UTC, erogluorhan approved these changes

2021-02-12 08:16 UTC, merged